const express = require('express')
const jwt = require('jsonwebtoken')
const router = express.Router()
const { userRegistration, addBroker, login } = require('../controllers/userController')
const { addDeposit, addTrade, addDividend, removeDeposit, removeTrade, removeDividend, updateDeposit, updateTrade, updateDividend } = require('../controllers/transactionHistory')
const { getTrade, getDeposit, getDividend } = require('../controllers/displayData')

router.post('/addUser', userRegistration)
router.put('/addBroker', addBroker)
router.put('/addDeposit', addDeposit)
router.put('/addTrade', addTrade)
router.put('/addDividend', addDividend)
router.put('/removeDeposit', removeDeposit)
router.put('/removeTrade', removeTrade)
router.put('/removeDividend', removeDividend)
router.put('/updateDeposit', updateDeposit)
router.put('/updateTrade', updateTrade)
router.put('updateDividend', updateDividend)
router.get('/getTrade/:id', getTrade)
router.get('/getDeposit/:id', getDeposit)
router.get('/getDividend/:id', getDividend)
router.post('/login', login)
module.exports = router